version: '3.8'

services:
    db:
        image: postgres:latest
        container_name: my_postgres
        environment:
            POSTGRES_USER: postgreuser
            POSTGRES_PASSWORD: password
            POSTGRES_DB: mydatabase
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

volumes:
    postgres_data:
        driver: local
