###
GET http://127.0.0.1:3030/questions

###
POST http://127.0.0.1:3030/questions
Content-Type: application/json

{
    "title": "How many countries are there in the world?",
    "content": "I want to know how many countries are there in the world.",
    "tags": ["general"]
}

###
POST http://127.0.0.1:3030/answers
Content-Type: application/x-www-form-urlencoded

question_id=1
&content=Paris is the capital of France