[package]
name = "handle-errors"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
tracing = { version = "0.1", features = ["log"] }
reqwest = "0.12"
reqwest-middleware = "0.4"
sqlx = { version = "0.8", features = ["postgres"] }
rust-argon2 = "2.0"
